branch-defaults:
  main:
    environment: app-vud-backend-dev
    group_suffix: null
global:
  application_name: app-vud-backend
  branch: null
  default_ec2_keyname: vub-back-deploy
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
