# Generated by Django 4.1.4 on 2024-02-20 16:20

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Grad Medical',
                'verbose_name_plural': 'Grade Medicale',
            },
        ),
        migrations.CreateModel(
            name='AddSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=footerlabels.models.upload_path_addsense_image)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Add Sense',
                'verbose_name_plural': 'Add-uri Sense',
            },
        ),
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_banner_image)),
            ],
            options={
                'verbose_name': 'Banner Card',
                'verbose_name_plural': 'Banners Cards',
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate Unitate',
                'verbose_name_plural': 'Specialitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='Footerlabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Eticheta Footer',
                'verbose_name_plural': 'Etichete Footer',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_facilities)),
            ],
            options={
                'verbose_name': 'Facilitate Unitate',
                'verbose_name_plural': 'Facilitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='MedicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Competenta',
                'verbose_name_plural': 'Competente',
            },
        ),
        migrations.CreateModel(
            name='MedicalUnityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tip Unitate Medicala',
                'verbose_name_plural': 'Tipuri Unitate Medicala',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Newsletter Email',
                'verbose_name_plural': 'Newsletter Emails',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate',
                'verbose_name_plural': 'Specialitati',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag Blog',
                'verbose_name_plural': 'Taguri Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titlu Postare')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_banner_image, verbose_name='Imagine Banner')),
                ('link_banner_image', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine Banner')),
                ('headline_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titlu Paragraf 1')),
                ('content_1', models.TextField(blank=True, null=True, verbose_name='Continut Paragraf 1')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_1_image, verbose_name='Imagine 1')),
                ('link_image_1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine 1')),
                ('headline_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titlu Paragraf 2')),
                ('content_2', models.TextField(blank=True, null=True, verbose_name='Continut paragraf 2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_2_image, verbose_name='Imagine 2')),
                ('link_image_2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine 2')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogposts', to='footerlabels.tag', verbose_name='Taguri postare')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
