# Generated by Django 4.1.4 on 2023-03-20 16:06

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Grad Academic',
                'verbose_name_plural': 'Grade Academice',
            },
        ),
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_banner_image)),
            ],
            options={
                'verbose_name': 'Banner Card',
                'verbose_name_plural': 'Banners Cards',
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate Unitate',
                'verbose_name_plural': 'Specialitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='Footerlabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Eticheta Footer',
                'verbose_name_plural': 'Etichete Footer',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_facilities)),
            ],
            options={
                'verbose_name': 'Facilitate Unitate',
                'verbose_name_plural': 'Facilitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='MedicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Competenta',
                'verbose_name_plural': 'Competente',
            },
        ),
        migrations.CreateModel(
            name='MedicalUnityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tip Unitate Medicala',
                'verbose_name_plural': 'Tipuri Unitate Medicala',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Newsletter Email',
                'verbose_name_plural': 'Newsletter Emails',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate',
                'verbose_name_plural': 'Specialitati',
            },
        ),
        migrations.CreateModel(
            name='CollaboratorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_collaborator_doctor)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_degree', models.ManyToManyField(to='footerlabels.academicdegree')),
                ('medical_skill', models.ManyToManyField(to='footerlabels.medicalskills')),
                ('speciality', models.ManyToManyField(to='footerlabels.speciality')),
            ],
            options={
                'verbose_name': 'Doctor Colaborator Clinica',
                'verbose_name_plural': 'Doctori Colaboratori Clinici',
            },
        ),
    ]
