# Generated by Django 4.1.4 on 2024-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicspecialities',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
