# Generated by Django 4.1.4 on 2023-04-03 22:49

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=footerlabels.models.upload_path_addsense_image)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Add Card',
                'verbose_name_plural': 'Add-uri Cards',
            },
        ),
    ]
