# Generated by Django 4.1.4 on 2023-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalUnityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
    ]
