# Generated by Django 4.1.4 on 2023-06-05 16:21

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0002_addsense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag Blog',
                'verbose_name_plural': 'Taguri Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_banner_image)),
                ('headline_1', models.CharField(max_length=255)),
                ('content_1', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_1_image)),
                ('headline_2', models.CharField(max_length=255)),
                ('content_2', models.TextField()),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_2_image)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='blogposts', to='footerlabels.tag')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
