# Generated by Django 4.1.4 on 2023-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0002_medicalunitytypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Grad Academic',
                'verbose_name_plural': 'Grade Academice',
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate Unitate',
                'verbose_name_plural': 'Specialitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='MedicalFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Facilitate Unitate',
                'verbose_name_plural': 'Facilitati Unitate',
            },
        ),
        migrations.CreateModel(
            name='MedicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Competenta',
                'verbose_name_plural': 'Competente',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialitate',
                'verbose_name_plural': 'Specialitati',
            },
        ),
        migrations.AlterModelOptions(
            name='footerlabels',
            options={'ordering': ['created'], 'verbose_name': 'Eticheta Footer', 'verbose_name_plural': 'Etichete Footer'},
        ),
        migrations.AlterModelOptions(
            name='medicalunitytypes',
            options={'verbose_name': 'Tip Unitate Medicala', 'verbose_name_plural': 'Tipuri Unitate Medicala'},
        ),
    ]
