# Generated by Django 4.1.4 on 2024-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0002_alter_clinicspecialities_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdegree',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalfacilities',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalskills',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalunitytypes',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
