# Generated by Django 4.1.4 on 2023-03-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0003_academicdegree_clinicspecialities_medicalfacilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/collaborator_doctor/')),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_degree', models.ManyToManyField(to='footerlabels.academicdegree')),
                ('medical_skill', models.ManyToManyField(to='footerlabels.medicalskills')),
                ('speciality', models.ManyToManyField(to='footerlabels.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/clinic_offices/')),
                ('medical_unit_types', models.ManyToManyField(to='footerlabels.medicalunitytypes')),
            ],
        ),
    ]
