# Generated by Django 4.1.4 on 2023-06-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_collaboratordoctor_clinic_collab_clinic_and_more'),
        ('footerlabels', '0003_tag_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaboratorDoctor',
        ),
    ]
