# Generated by Django 4.1.4 on 2024-01-29 16:51

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0005_alter_academicdegree_options_alter_addsense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link_banner_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine Banner'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link_image_1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine 1'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link_image_2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagine 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_banner_image, verbose_name='Imagine Banner'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_1',
            field=models.TextField(blank=True, null=True, verbose_name='Continut Paragraf 1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_2',
            field=models.TextField(blank=True, null=True, verbose_name='Continut paragraf 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='headline_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titlu Paragraf 1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='headline_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titlu Paragraf 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_1_image, verbose_name='Imagine 1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_blog_image_2_image, verbose_name='Imagine 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogposts', to='footerlabels.tag', verbose_name='Taguri postare'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titlu Postare'),
        ),
    ]
