# Generated by Django 4.1.4 on 2023-03-18 21:35

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0006_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_collaborator_doctor)),
            ],
            options={
                'verbose_name': 'Banner Card',
                'verbose_name_plural': 'Banners Cards',
            },
        ),
        migrations.AlterModelOptions(
            name='clinicoffice',
            options={'verbose_name': 'Sediu Clinica', 'verbose_name_plural': 'Sedii Clinici'},
        ),
        migrations.AlterModelOptions(
            name='collaboratordoctor',
            options={'verbose_name': 'Doctor Colaborator Clinica', 'verbose_name_plural': 'Doctori Colaboratori Clinici'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Email', 'verbose_name_plural': 'Newsletter Emails'},
        ),
    ]
