# Generated by Django 4.1.4 on 2023-03-18 22:55

from django.db import migrations, models
import footerlabels.models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0008_medicalfacilities_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercards',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=footerlabels.models.upload_path_banner_image),
        ),
    ]
