# Generated by Django 4.1.4 on 2023-03-20 17:58

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=authentication.models.upload_path_clinic_office),
        ),
    ]
