# Generated by Django 4.1.4 on 2023-02-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_clinic_company_clinic_role_user_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='company_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='town',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
