# Generated by Django 4.1.4 on 2023-03-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_requesttoredeemclinic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttoredeemclinic',
            options={'verbose_name': 'Revendica Clinica', 'verbose_name_plural': 'Revendica Clinici'},
        ),
    ]
