# Generated by Django 4.1.4 on 2024-09-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_clinic_step_alter_collaboratordoctor_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClinic',
            fields=[
            ],
            options={
                'verbose_name': 'Clinici De Aprobat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.clinic',),
        ),
        migrations.CreateModel(
            name='MyDoctors',
            fields=[
            ],
            options={
                'verbose_name': 'Doctori De Aprobat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.collaboratordoctor',),
        ),
    ]
