# Generated by Django 4.1.4 on 2023-06-06 11:29

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0003_tag_blogpost'),
        ('authentication', '0004_alter_requesttoredeemclinic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_path_collaborator_doctor)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('primary_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('website_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('website_google', models.CharField(blank=True, max_length=255, null=True)),
                ('website_linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('website_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('academic_degree', models.ManyToManyField(to='footerlabels.academicdegree')),
            ],
            options={
                'verbose_name': 'Doctor Colaborator Clinica',
                'verbose_name_plural': 'Doctori Colaboratori Clinici',
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='collab_clinic',
            field=models.ManyToManyField(blank=True, to='authentication.clinic'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='collaborator_clinic',
            field=models.ManyToManyField(blank=True, to='authentication.clinic'),
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='collaborator_doctor',
            field=models.ManyToManyField(blank=True, to='authentication.collaboratordoctor'),
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='medical_skill',
            field=models.ManyToManyField(to='footerlabels.medicalskills'),
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='speciality',
            field=models.ManyToManyField(to='footerlabels.speciality'),
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='collaborator_doctor',
            field=models.ManyToManyField(blank=True, to='authentication.collaboratordoctor'),
        ),
    ]
