# Generated by Django 4.1.4 on 2023-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_clinic_medical_unit_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
