# Generated by Django 4.1.4 on 2023-08-01 12:29
import csv
import json

from django.db import migrations, models
import django.utils.timezone

from authentication.models import Clinic
from footerlabels.models import MedicalUnityTypes, MedicalFacilities, ClinicSpecialities


def load_data_from_csv(apps, schema_editor):
    csv_file = 'authentication/csv/clinics_address.csv'

    with open(csv_file, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            clinic_name = row.get("clinic_name", "")
            clinic_street = row.get("clinic_street", "")
            clinic_number = row.get("clinic_number", "")
            clinic_city = row.get("clinic_city", "")
            clinic_county = row.get("clinic_county", "")
            clinic_other_details = row.get("clinic_other_details", "")

            try:
                clinic = Clinic.objects.get(clinic_name=clinic_name,)
                clinic.clinic_street = clinic_street
                clinic.clinic_number = clinic_number
                clinic.clinic_town = clinic_city
                clinic.clinic_county = clinic_county
                clinic.clinic_other_details = clinic_other_details
                clinic.save()
            except Exception as e:
                print(e)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_myclinic_mydoctors'),
    ]

    operations = [
        migrations.RunPython(load_data_from_csv),
    ]
