# Generated by Django 4.1.4 on 2023-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0004_delete_collaboratordoctor'),
        ('authentication', '0005_collaboratordoctor_clinic_collab_clinic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboratordoctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctori'},
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='academic_degree',
            field=models.ManyToManyField(blank=True, null=True, to='footerlabels.academicdegree'),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='medical_skill',
            field=models.ManyToManyField(blank=True, null=True, to='footerlabels.medicalskills'),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='speciality',
            field=models.ManyToManyField(blank=True, null=True, to='footerlabels.speciality'),
        ),
    ]
