# Generated by Django 4.1.4 on 2023-03-06 10:13

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_clinic_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_path_clinic),
        ),
    ]
