# Generated by Django 4.1.4 on 2023-03-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_clinic_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='step',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
