# Generated by Django 4.1.4 on 2023-06-08 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_doctorreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review Clinica', 'verbose_name_plural': 'Reviews Clinici'},
        ),
        migrations.AlterModelOptions(
            name='doctorreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review Doctor', 'verbose_name_plural': 'Reviews Doctori'},
        ),
        migrations.CreateModel(
            name='RequestToRedeemDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_to_redeem', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revendica Doctor',
                'verbose_name_plural': 'Revendica Doctori',
            },
        ),
    ]
