# Generated by Django 4.1.4 on 2023-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_clinicreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
