# Generated by Django 4.1.4 on 2023-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_clinic_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
