# Generated by Django 4.1.4 on 2023-06-11 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footerlabels', '0005_alter_academicdegree_options_alter_addsense_options_and_more'),
        ('authentication', '0010_alter_clinicreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttoredeemclinic',
            options={'verbose_name': 'Revendicare Clinica', 'verbose_name_plural': 'Revendicari Clinici'},
        ),
        migrations.AlterModelOptions(
            name='requesttoredeemdoctor',
            options={'verbose_name': 'Revendicare Doctor', 'verbose_name_plural': 'Revendicari Doctori'},
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='phone_vud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requesttoredeemclinic',
            name='accepted',
            field=models.CharField(choices=[('default', 'Neselectat'), ('acceptat', 'Acceptat'), ('respins', 'Respins')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='requesttoredeemdoctor',
            name='accepted',
            field=models.CharField(choices=[('default', 'Neselectat'), ('acceptat', 'Acceptat'), ('respins', 'Respins')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='academic_degree',
            field=models.ManyToManyField(blank=True, to='footerlabels.academicdegree'),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='medical_skill',
            field=models.ManyToManyField(blank=True, to='footerlabels.medicalskills'),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='footerlabels.speciality'),
        ),
        migrations.AlterField(
            model_name='collaboratordoctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
