# Generated by Django 4.1.4 on 2023-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_user_is_visible_clinic_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
