# Generated by Django 4.1.4 on 2024-02-14 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20230815_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboratordoctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
